// Candidate image mapping - loaded from frontend only
export const candidateImages: Record<string, string> = {
  "maguy-merine": "/dancers/MAGUY MERINE.jpeg",
  "kendi": "/dancers/KENDI.jpeg",
  "beb-s-velina": "/dancers/bebs-velina.jpeg",
  "katia-eg": "/dancers/Katia EG.png",
  "stella-officielle3": "/dancers/Stella Officielle3.jpeg",
  "nounours": "/dancers/Nounours.jpeg",
  "o-konor-celeste": "/dancers/O'konor Celeste.jpeg",
  "nelly-dora": "/dancers/NELLY DORA.jpeg",
  "chica-bassa": "/dancers/placeholder.svg",
  "lmn-ponce-off": "/dancers/placeholder.svg",
  "influence-femi": "/dancers/placeholder.svg",
  "jessi-237": "/dancers/placeholder.svg",
  "maxime-la-vitesse": "/dancers/Maxime la vitesse.jpg",
  "kloe-la-machine": "/dancers/placeholder.svg",
  "maldjess-peace": "/dancers/placeholder.svg",
  "jumeaux-de-la-capitale": "/dancers/placeholder.svg",
  "etienne-kampos": "/dancers/Etienne kampos.jpg",
  "de-flow": "/dancers/De Flow.jpeg",
  "pascal-metaphore": "/dancers/PASCAL métaphore.jpeg",
  "el-fally-du-237": "/dancers/El fally du 237.jpg",
  "escram-shuwingum": "/dancers/placeholder.svg",
  "petit-tchakap": "/dancers/petit tchakap.jpg",
  "3-peace": "/dancers/3 peace.jpeg",
  "jkaxel": "/dancers/JKAXEL.jpg",
  "deboy-le-monstre": "/dancers/DEBOY LE MONSTRE.jpeg",
  "el-fally-237": "/dancers/El fally du 237.jpg",
  "afu-dance-academie": "/dancers/AFU DANCE ACADEMY STUDIO.jpeg",
  "etat-nwar-dance": "/dancers/ÉTAT NWAR DANCE SCHOOL.jpg",
  "team-escram": "/dancers/TEAM ESCRAM.jpeg",
  "mbole-dancing": "/dancers/Mbole Dancing.jpeg",
  "ordinateur-baboue": "/dancers/ORDINATEUR baboué.jpeg",
  "shazam-le-vrai": "/dancers/SHAZAM.jpeg",
  "xender": "/dancers/XENDER.jpeg",
  "bb-super-l-elu": "/dancers/placeholder.svg",
  "vinny-magicien": "/dancers/placeholder.svg",
  "smobar-le-balthazar": "/dancers/placeholder.svg",
  "authentik": "/dancers/placeholder.svg",
  "pikan-pointure": "/dancers/Pikan pointu.jpeg",
  "wenjel-avataro": "/dancers/Wenjel Avataro.jpeg",
  "jesus-saotao": "/dancers/placeholder.svg",
  "tks-officiel": "/dancers/TKS OFFICIEL.jpg",
  "4-peace": "/dancers/placeholder.svg",
  "echantillon-1er": "/dancers/placeholder.svg",
  "yvan-10": "/dancers/placeholder.svg",
  "nyanga-boy": "/dancers/placeholder.svg",
  "tresor-brown": "/dancers/placeholder.svg",
  "ayi-ventilateur": "/dancers/ayi ventilateur.png",
  "nounours-traditionnel": "/dancers/placeholder.svg",
  "arcadien-fureur": "/dancers/Accadient Fureur.jpeg",
  "kibong-adoube": "/dancers/placeholder.svg",
  "accadien-fureur": "/dancers/Accadient Fureur.jpeg",
  "goldy-lastar": "/dancers/GOLDY LA-STAR.jpeg",
  "garcon-determine": "/dancers/Garçon déterminé.jpg",
  "la-religion-noire": "/dancers/placeholder.svg",
  "le-hempe": "/dancers/placeholder.svg",
  "deboy-le-monstre-et-maguy-merine": "/dancers/DEBOY LE MONSTRE.jpeg",
  "4-peace-et-rachel-elegance": "/dancers/placeholder.svg",
  "chica-bassa-et-kendi": "/dancers/KENDI.jpeg",
  "tks-officiel-et-tresor-brown": "/dancers/TKS OFFICIEL.jpg",
  "el-fally-du-237-et-davia-off": "/dancers/El fally du 237.jpg",
  "o-konor-celeste-et-katiaeg": "/dancers/O'konor Celeste.jpeg",
  "3-peace-et-influence-femi": "/dancers/3 peace.jpeg",
};

export function getCandidateImage(candidateId: string): string {
  return candidateImages[candidateId] || "/dancers/placeholder.svg";
}
