// Complete list of all 67 candidates from Firebase
export const allCandidatesData = [
  {
    name: "Maguy merine",
    title: "Dance Star",
    image: "/dancers/maguy-merine.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse féminine",
  },
  {
    name: "Kendi",
    title: "Dance Performer",
    image: "/dancers/kendi.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse féminine",
  },
  {
    name: "Beb's velina",
    title: "Talented Dancer",
    image: "/dancers/bebs-velina.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse féminine",
  },
  {
    name: "Katia eg",
    title: "Professional Artist",
    image: "/dancers/katia-eg.png",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse féminine",
  },
  {
    name: "Stella officielle3",
    title: "Star Dancer",
    image: "/dancers/stella-officielle3.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse féminine",
  },
  {
    name: "Nounours",
    title: "Performer",
    image: "/dancers/nounours.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse féminine",
  },
  {
    name: "O'konor Céleste",
    title: "Dancer",
    image: "/dancers/okonor-celeste.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse féminine",
  },
  {
    name: "Nelly Dora",
    title: "Mbolé Dancer",
    image: "/dancers/nelly-dora.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse mbolé",
  },
  {
    name: "Chica bassa",
    title: "Mbolé Artist",
    image: "/dancers/chica-bassa.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse mbolé",
  },
  {
    name: "LMN ponce Off",
    title: "Dancer",
    image: "/dancers/lmn-ponce-off.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse mbolé",
  },
  {
    name: "Influence Femi",
    title: "Performer",
    image: "/dancers/influence-femi.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse mbolé",
  },
  {
    name: "Jessi 237",
    title: "Dancer",
    image: "/dancers/jessi-237.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse mbolé",
  },
  {
    name: "Maxime la vitesse",
    title: "Young Dancer",
    image: "/dancers/maxime-la-vitesse.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste jeune danseur/danseuse",
  },
  {
    name: "Kloe la machine",
    title: "Young Artist",
    image: "/dancers/kloe-la-machine.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste jeune danseur/danseuse",
  },
  {
    name: "Meldjess peace",
    title: "Young Performer",
    image: "/dancers/meldjess-peace.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste jeune danseur/danseuse",
  },
  {
    name: "Jumeaux de la capitale",
    title: "Twin Stars",
    image: "/dancers/jumeaux-capitale.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste jeune danseur/danseuse",
  },
  {
    name: "Déboy le monstre",
    title: "Web Performer",
    image: "/dancers/deboy-le-monstre.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur Performance web",
  },
  {
    name: "El fally 237",
    title: "Web Artist",
    image: "/dancers/el-fally-du-237.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur Performance web",
  },
  {
    name: "Jkaxel",
    title: "Web Dancer",
    image: "/dancers/jkaxel.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur Performance web",
  },
  {
    name: "Étienne kampos",
    title: "Web Performer",
    image: "/dancers/etienne-kampos.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur Performance web",
  },
  {
    name: "AFU Dance académie",
    title: "Dance Group",
    image: "/dancers/afu-dance-academy.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur Groupe de danse",
  },
  {
    name: "Etat NWAR dance",
    title: "Dance Group",
    image: "/dancers/etat-nwar-dance.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur Groupe de danse",
  },
  {
    name: "Team Escram",
    title: "Dance Group",
    image: "/dancers/team-escram.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur Groupe de danse",
  },
  {
    name: "Mbolé Dancing",
    title: "Dance Group",
    image: "/dancers/mbole-dancing.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur Groupe de danse",
  },
  {
    name: "Ordinateur baboué",
    title: "Afro Coupé Décalé",
    image: "/dancers/ordinateur-baboue.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur Afro Coupé décalé",
  },
  {
    name: "Shazam le vrai",
    title: "Afro Coupé Décalé",
    image: "/dancers/shazam.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur Afro Coupé décalé",
  },
  {
    name: "Xender",
    title: "Afro Coupé Décalé",
    image: "/dancers/xender.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur Afro Coupé décalé",
  },
  {
    name: "BB Super l'elu",
    title: "Afro Coupé Décalé",
    image: "/dancers/bb-super-lelu.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur Afro Coupé décalé",
  },
  {
    name: "Vinny magicien",
    title: "Afro Coupé Décalé",
    image: "/dancers/vinny-magicien.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur Afro Coupé décalé",
  },
  {
    name: "Smobar Le Balthazar",
    title: "Afro Coupé Décalé",
    image: "/dancers/smobar-le-balthazar.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur Afro Coupé décalé",
  },
  {
    name: "Authentik",
    title: "Afro Coupé Décalé",
    image: "/dancers/authentik.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur Afro Coupé décalé",
  },
  {
    name: "Pikan pointu",
    title: "Afro Coupé Décalé",
    image: "/dancers/pikan-pointu.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur Afro Coupé décalé",
  },
  {
    name: "Wenjel Avataro",
    title: "Afro Coupé Décalé",
    image: "/dancers/wenjel-avataro.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur Afro Coupé décalé",
  },
  {
    name: "Jesus saotao",
    title: "Afro Coupé Décalé",
    image: "/dancers/jesus-saotao.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur Afro Coupé décalé",
  },
  {
    name: "Étienne kampos",
    title: "Male Dancer",
    image: "/dancers/etienne-kampos.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur - masculin",
  },
  {
    name: "De Flow",
    title: "Male Dancer",
    image: "/dancers/de-flow.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur - masculin",
  },
  {
    name: "Pascal métaphore",
    title: "Male Dancer",
    image: "/dancers/pascal-metaphore.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur - masculin",
  },
  {
    name: "El Fally du 237",
    title: "Male Dancer",
    image: "/dancers/el-fally-du-237.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur - masculin",
  },
  {
    name: "Escram shuwingum",
    title: "Male Dancer",
    image: "/dancers/escram.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur - masculin",
  },
  {
    name: "Petit tchakap",
    title: "Male Dancer",
    image: "/dancers/petit-tchakap.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur - masculin",
  },
  {
    name: "3 peace",
    title: "Male Dancer",
    image: "/dancers/3-peace.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur - masculin",
  },
  {
    name: "Jkaxel",
    title: "Male Dancer",
    image: "/dancers/jkaxel.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur - masculin",
  },
  {
    name: "Déboy le monstre",
    title: "Mbolé Dancer",
    image: "/dancers/deboy-le-monstre.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "meilleurs artiste danseurs mbolé",
  },
  {
    name: "Tks officiel",
    title: "Mbolé Dancer",
    image: "/dancers/tks-officiel.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "meilleurs artiste danseurs mbolé",
  },
  {
    name: "4 peace",
    title: "Mbolé Dancer",
    image: "/dancers/4-peace.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "meilleurs artiste danseurs mbolé",
  },
  {
    name: "Nyanga Boy",
    title: "Mbolé Dancer",
    image: "/dancers/nyanga-boy.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "meilleurs artiste danseurs mbolé",
  },
  {
    name: "Trésor brown",
    title: "Mbolé Dancer",
    image: "/dancers/tresor-brown.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "meilleurs artiste danseurs mbolé",
  },
  {
    name: "Ayi ventilateur",
    title: "Folklorique Dancer",
    image: "/dancers/ayi-ventilateur.png",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur au rythme folklorique",
  },
  {
    name: "Nounours traditionnel",
    title: "Folklorique Dancer",
    image: "/dancers/nounours-traditionnel.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur au rythme folklorique",
  },
  {
    name: "Arcadien fureur",
    title: "Folklorique Dancer",
    image: "/dancers/accadien-fureur.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur au rythme folklorique",
  },
  {
    name: "Kibong adoube",
    title: "Folklorique Dancer",
    image: "/dancers/kibong-adoube.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur au rythme folklorique",
  },
  {
    name: "Goldy lastar",
    title: "Choreographer",
    image: "/dancers/goldy-lastar.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste Chorégraphe",
  },
  {
    name: "Garçon déterminé",
    title: "Choreographer",
    image: "/dancers/garcon-determine.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste Chorégraphe",
  },
  {
    name: "La religion noire",
    title: "Choreographer",
    image: "/dancers/religion-noir.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste Chorégraphe",
  },
  {
    name: "Le Hempe",
    title: "Choreographer",
    image: "/dancers/le-hempe.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste Chorégraphe",
  },
  {
    name: "Déboy le monstre et Maguy merine",
    title: "Duo",
    image: "/dancers/deboy-le-monstre.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur collaboration duo",
  },
  {
    name: "4 peace et Rachel élégance",
    title: "Duo",
    image: "/dancers/4-peace.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur collaboration duo",
  },
  {
    name: "Chica bassa et kendi",
    title: "Duo",
    image: "/dancers/chica-bassa.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur collaboration duo",
  },
  {
    name: "Tks officiel et Trésor brown",
    title: "Duo",
    image: "/dancers/tks-officiel.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur collaboration duo",
  },
  {
    name: "El fally du 237 et davia off",
    title: "Duo",
    image: "/dancers/el-fally-du-237.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur collaboration duo",
  },
  {
    name: "O'konor Celeste et Katia_eg",
    title: "Duo",
    image: "/dancers/okonor-celeste.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur collaboration duo",
  },
  {
    name: "3 peace et Influence femi",
    title: "Duo",
    image: "/dancers/3-peace.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur collaboration duo",
  },
  {
    name: "Accadien fureur",
    title: "Choreographer",
    image: "/dancers/accadien-fureur.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste Chorégraphe",
  },
  {
    name: "El Fally du 237",
    title: "Dancer of the Year",
    image: "/dancers/el-fally-du-237.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur de l'année",
  },
  {
    name: "BB Super l'elu",
    title: "Dancer of the Year",
    image: "/dancers/bb-super-lelu.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur de l'année",
  },
  {
    name: "Déboy le monstre",
    title: "Dancer of the Year",
    image: "/dancers/deboy-le-monstre.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur de l'année",
  },
  {
    name: "Escram shuwingum",
    title: "Dancer of the Year",
    image: "/dancers/escram.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur de l'année",
  },
  {
    name: "Shazam le vrai",
    title: "Dancer of the Year",
    image: "/dancers/shazam.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur de l'année",
  },
  {
    name: "Kibong adoube",
    title: "Dancer of the Year",
    image: "/dancers/kibong-adoube.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur de l'année",
  },
  {
    name: "Katia eg",
    title: "Female Dancer of the Year",
    image: "/dancers/katia-eg.png",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse de l'année",
  },
  {
    name: "Kendi",
    title: "Female Dancer of the Year",
    image: "/dancers/kendi.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse de l'année",
  },
  {
    name: "Beb's velina",
    title: "Female Dancer of the Year",
    image: "/dancers/bebs-velina.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse de l'année",
  },
  {
    name: "Maguy merine",
    title: "Female Dancer of the Year",
    image: "/dancers/maguy-merine.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse de l'année",
  },
  {
    name: "O'konor Céleste",
    title: "Female Dancer of the Year",
    image: "/dancers/okonor-celeste.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse de l'année",
  },
  {
    name: "Nelly Dora",
    title: "Web Performer",
    image: "/dancers/nelly-dora.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur Performance web",
  },
  {
    name: "Chica bassa",
    title: "Web Performer",
    image: "/dancers/chica-bassa.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur Performance web",
  },
  {
    name: "Maguy merine",
    title: "Web Performer",
    image: "/dancers/maguy-merine.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur Performance web",
  },
  {
    name: "Jessi 237",
    title: "Web Performer",
    image: "/dancers/jessi-237.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur Performance web",
  },
  {
    name: "Petit tchakap",
    title: "Mbolé Dancer",
    image: "/dancers/petit-tchakap.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "meilleurs artiste danseurs mbolé",
  },
  {
    name: "El fally du 237",
    title: "Mbolé Dancer",
    image: "/dancers/el-fally-du-237.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "meilleurs artiste danseurs mbolé",
  },
  {
    name: "Echantillon 1er",
    title: "Mbolé Dancer",
    image: "/dancers/echantillon-1er.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "meilleurs artiste danseurs mbolé",
  },
  {
    name: "Yvan 10",
    title: "Mbolé Dancer",
    image: "/dancers/yvan-10.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "meilleurs artiste danseurs mbolé",
  },
  {
    name: "Maguy merine",
    title: "Mbolé Dancer",
    image: "/dancers/maguy-merine.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse mbolé",
  },
  {
    name: "Kendi",
    title: "Mbolé Dancer",
    image: "/dancers/kendi.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleure artiste danseuse mbolé",
  },
  {
    name: "Meilleur Groupe de danse - AFU",
    title: "Dance Group",
    image: "/dancers/afu-dance-academy.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur groupe de danse",
  },
  {
    name: "Meilleur Groupe de danse - NWAR",
    title: "Dance Group",
    image: "/dancers/etat-nwar-dance.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur groupe de danse",
  },
  {
    name: "Meilleur Groupe de danse - Team Escram",
    title: "Dance Group",
    image: "/dancers/team-escram.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur groupe de danse",
  },
  {
    name: "Meilleur Groupe de danse - Mbolé",
    title: "Dance Group",
    image: "/dancers/mbole-dancing.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur groupe de danse",
  },
  {
    name: "Meilleur artiste danseur mbolé - Petit tchakap",
    title: "Mbolé Dancer",
    image: "/dancers/petit-tchakap.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur mbolé",
  },
  {
    name: "Meilleur artiste danseur mbolé - Déboy",
    title: "Mbolé Dancer",
    image: "/dancers/deboy-le-monstre.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur mbolé",
  },
  {
    name: "Meilleur artiste danseur mbolé - El Fally",
    title: "Mbolé Dancer",
    image: "/dancers/el-fally-du-237.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur mbolé",
  },
  {
    name: "Meilleur artiste danseur mbolé - TKS",
    title: "Mbolé Dancer",
    image: "/dancers/tks-officiel.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur mbolé",
  },
  {
    name: "Meilleur artiste danseur mbolé - 4 peace",
    title: "Mbolé Dancer",
    image: "/dancers/4-peace.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur mbolé",
  },
  {
    name: "Meilleur artiste danseur Afro Coupé - Ordinateur",
    title: "Afro Coupé Décalé",
    image: "/dancers/ordinateur-baboue.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur Afro Coupé décalé",
  },
  {
    name: "Meilleur artiste danseur Afro Coupé - Shazam",
    title: "Afro Coupé Décalé",
    image: "/dancers/shazam.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur Afro Coupé décalé",
  },
  {
    name: "Meilleur artiste danseur Afro Coupé - Xender",
    title: "Afro Coupé Décalé",
    image: "/dancers/xender.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur Afro Coupé décalé",
  },
  {
    name: "Meilleur artiste danseur Afro Coupé - BB Super",
    title: "Afro Coupé Décalé",
    image: "/dancers/bb-super-lelu.jpeg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur Afro Coupé décalé",
  },
  {
    name: "Meilleur artiste danseur Afro Coupé - Vinny",
    title: "Afro Coupé Décalé",
    image: "/dancers/vinny-magicien.jpg",
    votes: 0,
    badge: null,
    percentage: 0,
    category: "Meilleur artiste danseur Afro Coupé décalé",
  },
]
