// Candidate image mapping - loaded from frontend only
export const candidateImages: Record<string, string> = {
  "maguy-merine": "/dancers/maguy-merine.jpeg",
  "kendi": "/dancers/kendi.jpeg",
  "beb-s-velina": "/dancers/bebs-velina.jpeg",
  "katia-eg": "/dancers/katia-eg.png",
  "stella-officielle3": "/dancers/stella-officielle3.jpeg",
  "nounours": "/dancers/nounours.jpeg",
  "o-konor-celeste": "/dancers/okonor-celeste.jpeg",
  "nelly-dora": "/dancers/nelly-dora.jpeg",
  "chica-bassa": "/dancers/chica-bassa.jpeg",
  "lmn-ponce-off": "/dancers/lmn-ponce-off.jpeg",
  "influence-femi": "/dancers/influence-femi.jpeg",
  "jessi-237": "/dancers/jessi-237.jpeg",
  "maxime-la-vitesse": "/dancers/maxime-la-vitesse.jpg",
  "kloe-la-machine": "/dancers/kloe-la-machine.jpg",
  "maldjess-peace": "/dancers/meldjess-peace.jpeg",
  "jumeaux-de-la-capitale": "/dancers/jumeaux-capitale.jpg",
  "etienne-kampos": "/dancers/etienne-kampos.jpg",
  "de-flow": "/dancers/de-flow.jpeg",
  "pascal-metaphore": "/dancers/pascal-metaphore.jpeg",
  "el-fally-du-237": "/dancers/el-fally-du-237.jpg",
  "escram-shuwingum": "/dancers/escram.jpeg",
  "petit-tchakap": "/dancers/petit-tchakap.jpg",
  "3-peace": "/dancers/3-peace.jpeg",
  "jkaxel": "/dancers/jkaxel.jpg",
  "deboy-le-monstre": "/dancers/deboy-le-monstre.jpeg",
  "el-fally-237": "/dancers/el-fally-du-237.jpg",
  "afu-dance-academie": "/dancers/afu-dance-academy.jpeg",
  "etat-nwar-dance": "/dancers/etat-nwar-dance.jpg",
  "team-escram": "/dancers/team-escram.jpeg",
  "mbole-dancing": "/dancers/mbole-dancing.jpeg",
  "ordinateur-baboue": "/dancers/ordinateur-baboue.jpeg",
  "shazam-le-vrai": "/dancers/shazam.jpeg",
  "xender": "/dancers/xender.jpeg",
  "bb-super-l-elu": "/dancers/bb-super-lelu.jpeg",
  "vinny-magicien": "/dancers/vinny-magicien.jpg",
  "smobar-le-balthazar": "/dancers/smobar-le-balthazar.jpg",
  "authentik": "/dancers/authentik.jpg",
  "pikan-pointure": "/dancers/pikan-pointu.jpeg",
  "wenjel-avataro": "/dancers/wenjel-avataro.jpeg",
  "jesus-saotao": "/dancers/jesus-saotao.jpeg",
  "tks-officiel": "/dancers/tks-officiel.jpg",
  "4-peace": "/dancers/4-peace.jpeg",
  "echantillon-1er": "/dancers/echantillon-1er.jpeg",
  "yvan-10": "/dancers/yvan-10.jpeg",
  "nyanga-boy": "/dancers/nyanga-boy.jpeg",
  "tresor-brown": "/dancers/tresor-brown.jpeg",
  "ayi-ventilateur": "/dancers/ayi-ventilateur.png",
  "nounours-traditionnel": "/dancers/nounours-traditionnel.jpeg",
  "arcadien-fureur": "/dancers/accadien-fureur.jpeg",
  "kibong-adoube": "/dancers/kibong-adoube.jpeg",
  "accadien-fureur": "/dancers/accadien-fureur.jpeg",
  "goldy-lastar": "/dancers/goldy-lastar.jpeg",
  "garcon-determine": "/dancers/garcon-determine.jpg",
  "la-religion-noire": "/dancers/religion-noir.jpg",
  "le-hempe": "/dancers/le-hempe.jpg",
  "deboy-le-monstre-et-maguy-merine": "/dancers/deboy-le-monstre.jpeg",
  "4-peace-et-rachel-elegance": "/dancers/4-peace.jpeg",
  "chica-bassa-et-kendi": "/dancers/kendi.jpeg",
  "tks-officiel-et-tresor-brown": "/dancers/tks-officiel.jpg",
  "el-fally-du-237-et-davia-off": "/dancers/el-fally-du-237.jpg",
  "o-konor-celeste-et-katiaeg": "/dancers/okonor-celeste.jpeg",
  "3-peace-et-influence-femi": "/dancers/3-peace.jpeg",
};

export function getCandidateImage(candidateId: string): string {
  return candidateImages[candidateId] || "/dancers/placeholder.svg";
}
